### ISSUE TITLE
general question about your experience building this project

### ISSUE THREAD

**Issue by ghost** [desi-programmer/flutter_password_manager#1]
Hi @desi-programmer  ,

Hope you are all well !

I would like to create a clone of [teampass](https://github.com/nilsteampassnet/TeamPass) a collaborative password manager, and I was wondering if you knew or can explain how to create a catalog of items, organised with an [animated tree view](https://github.com/embraceitmobile/animated_tree_view), and [flutter_rbac](https://github.com/wilpar/flutter_rbac) for managing roles and permissions. From your experience, what advices would you give me for neat architecture.

Thanks for any insights or inputs on that question.

teampass screeenshot:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143676762-88e5e5c0-6a3e-473f-adae-09d9ae274f18.png)

Cheers,
Luc

**Comment by desi-programmer** [comment]
Hey @lucmichalski 

Hope you are good too.

I have never used Teampass, So I don't know the exact details there, although as I can see from their repo, they are most probably using PHP.

Coming to your project , You should mention What kind of backend are you going to use ?

a. In app local databse
b. a PAAS or BAAS like firebase
c. custom backend server , APIs and database.

No , matter what you use, for app code architecture, it depends on what State management technique you use. Go with provider or bloc or getx or riverpod.

# Roles 

You can use some 3rd part service or your way to manage user roles and what they can do and they can't. Access and deletion.

# Password Integrity 

You need to store the password safely. trick part is to use any kind of key-bases encryption and decryption. ( probably using the user master password in they key ).

# Grouping / Organization

Create your own categories, and group them however you like, social, work, family , whatever it is. 
UI can be achieved easily with flutter, You can be creative and put something of your own too. Like a dashboard, drawer, Expansion tile etc.

Hope it helps. !!
